<?php

use Illuminate\Database\Seeder;

class MunicipalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('municipality')->insert([
        	['id_departament' => 1,'municipality'=> 'Guatemala'],
			['id_departament' => 1,'municipality'=> 'Santa Catarina Pinula'],
			['id_departament' => 1,'municipality'=> 'San José Pinula'],
			['id_departament' => 1,'municipality'=> 'San José Del Golfo'],
			['id_departament' => 1,'municipality'=> 'Palencia'],
			['id_departament' => 1,'municipality'=> 'Chinautla'],
			['id_departament' => 1,'municipality'=> 'San Pedro Ayampuc'],
			['id_departament' => 1,'municipality'=> 'Mixco'],
			['id_departament' => 1,'municipality'=> 'San Pedro Sacatepéquez'],
			['id_departament' => 1,'municipality'=> 'San Juan Sacatepéquez'],
			['id_departament' => 1,'municipality'=> 'San Raymundo'],
			['id_departament' => 1,'municipality'=> 'Chuarrancho'],
			['id_departament' => 1,'municipality'=> 'Fraijanes'],
			['id_departament' => 1,'municipality'=> 'Amatitlán'],
			['id_departament' => 1,'municipality'=> 'Villa Nueva'],
			['id_departament' => 1,'municipality'=> 'Villa Canales'],
			['id_departament' => 1,'municipality'=> 'San Miguel Petapa'],
			['id_departament' => 2,'municipality'=> 'Guastatoya'],
			['id_departament' => 2,'municipality'=> 'Morazan'],
			['id_departament' => 2,'municipality'=> 'San Agustin Acasaguastlán'],
			['id_departament' => 2,'municipality'=> 'San Cristobal Acasaguastlán'],
			['id_departament' => 2,'municipality'=> 'El Jícaro'],
			['id_departament' => 2,'municipality'=> 'Sansare'],
			['id_departament' => 2,'municipality'=> 'Sanarate'],
			['id_departament' => 2,'municipality'=> 'San Antonio La Paz'],
			['id_departament' => 3,'municipality'=> 'Antigua'],
			['id_departament' => 3,'municipality'=> 'Jocotenango'],
			['id_departament' => 3,'municipality'=> 'Pastores'],
			['id_departament' => 3,'municipality'=> 'Sumpango'],
			['id_departament' => 3,'municipality'=> 'Santo Domingo Xenacoj'],
			['id_departament' => 3,'municipality'=> 'Santiago Sacatepéquez'],
			['id_departament' => 3,'municipality'=> 'San Bartolomé Milpas Altas'],
			['id_departament' => 3,'municipality'=> 'San Lucas Sacatepéquez'],
			['id_departament' => 3,'municipality'=> 'Santa Lucia Milpas Altas'],
			['id_departament' => 3,'municipality'=> 'Magdalena Milpas Altas'],
			['id_departament' => 3,'municipality'=> 'Santa María De Jesús'],
			['id_departament' => 3,'municipality'=> 'Ciudad Vieja'],
			['id_departament' => 3,'municipality'=> 'San Miguel Duenas'],
			['id_departament' => 3,'municipality'=> 'Alotenango'],
			['id_departament' => 3,'municipality'=> 'San Antonio Aguas Calientes'],
			['id_departament' => 3,'municipality'=> 'Santa Catarina Barahona'],
			['id_departament' => 4,'municipality'=> 'Chimaltenango'],
			['id_departament' => 4,'municipality'=> 'San Jose Poaquil'],
			['id_departament' => 4,'municipality'=> 'San Martin Jilotepeque'],
			['id_departament' => 4,'municipality'=> 'San Juan Comalapa'],
			['id_departament' => 4,'municipality'=> 'Santa Apolonia'],
			['id_departament' => 4,'municipality'=> 'Tecpán Guatemala'],
			['id_departament' => 4,'municipality'=> 'Patzún'],
			['id_departament' => 4,'municipality'=> 'San Miguel Pochuta'],
			['id_departament' => 4,'municipality'=> 'Patzicía'],
			['id_departament' => 4,'municipality'=> 'Santa Cruz Balanya'],
			['id_departament' => 4,'municipality'=> 'Acatenango'],
			['id_departament' => 4,'municipality'=> 'San Pedro Yepocapa'],
			['id_departament' => 4,'municipality'=> 'San Andrés Itzapa'],
			['id_departament' => 4,'municipality'=> 'Parramos'],
			['id_departament' => 4,'municipality'=> 'Zaragoza'],
			['id_departament' => 4,'municipality'=> 'El Tejar '],
			['id_departament' => 5,'municipality'=> 'Escuintla'],
			['id_departament' => 5,'municipality'=> 'Santa Lucia Cotzumalguapa'],
			['id_departament' => 5,'municipality'=> 'La Democracia'],
			['id_departament' => 5,'municipality'=> 'Siquinalá'],
			['id_departament' => 5,'municipality'=> 'Masagua'],
			['id_departament' => 5,'municipality'=> 'Tiquisate'],
			['id_departament' => 5,'municipality'=> 'La Gomera'],
			['id_departament' => 5,'municipality'=> 'Guanagazapa'],
			['id_departament' => 5,'municipality'=> 'San José'],
			['id_departament' => 5,'municipality'=> 'Iztapa'],
			['id_departament' => 5,'municipality'=> 'Palín'],
			['id_departament' => 5,'municipality'=> 'San Vicente Pacaya'],
			['id_departament' => 5,'municipality'=> 'Nueva Concepción'],
			['id_departament' => 6,'municipality'=> 'Cuilapa'],
			['id_departament' => 6,'municipality'=> 'Barberena'],
			['id_departament' => 6,'municipality'=> 'Santa Rosa De Lima'],
			['id_departament' => 6,'municipality'=> 'Casillas'],
			['id_departament' => 6,'municipality'=> 'San Rafael Las Flores'],
			['id_departament' => 6,'municipality'=> 'Oratorio'],
			['id_departament' => 6,'municipality'=> 'San Juan Tecuaco'],
			['id_departament' => 6,'municipality'=> 'Chiquimulilla'],
			['id_departament' => 6,'municipality'=> 'Taxisco'],
			['id_departament' => 6,'municipality'=> 'Santa María Ixhuatan'],
			['id_departament' => 6,'municipality'=> 'Guazacapan'],
			['id_departament' => 6,'municipality'=> 'Santa Cruz Naranjo'],
			['id_departament' => 6,'municipality'=> 'Pueblo Nuevo Viñas'],
			['id_departament' => 6,'municipality'=> 'Nueva Santa Rosa'],
			['id_departament' => 7,'municipality'=> 'Sololá'],
			['id_departament' => 7,'municipality'=> 'San José Chacaya'],
			['id_departament' => 7,'municipality'=> 'Santa María Visitación'],
			['id_departament' => 7,'municipality'=> 'Santa Lucia Utatlán'],
			['id_departament' => 7,'municipality'=> 'Nahuala'],
			['id_departament' => 7,'municipality'=> 'Santa Catarina Ixtahuacan'],
			['id_departament' => 7,'municipality'=> 'Santa Clara La Laguna'],
			['id_departament' => 7,'municipality'=> 'Concepción'],
			['id_departament' => 7,'municipality'=> 'San Andrés Semetabaj'],
			['id_departament' => 7,'municipality'=> 'Panajachel'],
			['id_departament' => 7,'municipality'=> 'Santa Catarina Palopó'],
			['id_departament' => 7,'municipality'=> 'San Antonio Palopó'],
			['id_departament' => 7,'municipality'=> 'San Lucas Tolimán'],
			['id_departament' => 7,'municipality'=> 'Santa Cruz La Laguna'],
			['id_departament' => 7,'municipality'=> 'San Pablo La Laguna'],
			['id_departament' => 7,'municipality'=> 'San Marcos La Laguna'],
			['id_departament' => 7,'municipality'=> 'San Juan La Laguna'],
			['id_departament' => 7,'municipality'=> 'San Pedro La Laguna'],
			['id_departament' => 7,'municipality'=> 'Santiago Atitlán'],
			['id_departament' => 8,'municipality'=> 'Totonicapán'],
			['id_departament' => 8,'municipality'=> 'San Cristóbal Totonicapán'],
			['id_departament' => 8,'municipality'=> 'San Francisco El Alto'],
			['id_departament' => 8,'municipality'=> 'San Andrés Xecul'],
			['id_departament' => 8,'municipality'=> 'Momostenango'],
			['id_departament' => 8,'municipality'=> 'Santa María Chiquimula'],
			['id_departament' => 8,'municipality'=> 'Santa Lucia La Reforma'],
			['id_departament' => 8,'municipality'=> 'San Bartolo Aguas Calientes '],
			['id_departament' => 9,'municipality'=> 'Quetzaltenango'],
			['id_departament' => 9,'municipality'=> 'Salcajá'],
			['id_departament' => 9,'municipality'=> 'Olintepeque'],
			['id_departament' => 9,'municipality'=> 'San Carlos Sija'],
			['id_departament' => 9,'municipality'=> 'Sibilia'],
			['id_departament' => 9,'municipality'=> 'Cabrican'],
			['id_departament' => 9,'municipality'=> 'Cajola'],
			['id_departament' => 9,'municipality'=> 'San Miguel Siguila'],
			['id_departament' => 9,'municipality'=> 'San Juan Ostuncalco'],
			['id_departament' => 9,'municipality'=> 'San Mateo'],
			['id_departament' => 9,'municipality'=> 'Concepción Chiquirichapa'],
			['id_departament' => 9,'municipality'=> 'San Martin Sacatepéquez'],
			['id_departament' => 9,'municipality'=> 'Almolonga'],
			['id_departament' => 9,'municipality'=> 'Cantel'],
			['id_departament' => 9,'municipality'=> 'Huitan'],
			['id_departament' => 9,'municipality'=> 'Zunil'],
			['id_departament' => 9,'municipality'=> 'Colomba Costa Cuca'],
			['id_departament' => 9,'municipality'=> 'San Francisco La Unión'],
			['id_departament' => 9,'municipality'=> 'El Palmar'],
			['id_departament' => 9,'municipality'=> 'Coatepeque'],
			['id_departament' => 9,'municipality'=> 'Genova Costa Cuca'],
			['id_departament' => 9,'municipality'=> 'Flores Costa Cuca'],
			['id_departament' => 9,'municipality'=> 'La Esperanza'],
			['id_departament' => 9,'municipality'=> 'Palestina De Los Altos'],
			['id_departament' => 10,'municipality'=> 'Mazatenango'],
			['id_departament' => 10,'municipality'=> 'Cuyotenango'],
			['id_departament' => 10,'municipality'=> 'San Francisco Zapotitlan'],
			['id_departament' => 10,'municipality'=> 'San Bernardino'],
			['id_departament' => 10,'municipality'=> 'San José El Idolo'],
			['id_departament' => 10,'municipality'=> 'Santo Domingo Suchitepéquez'],
			['id_departament' => 10,'municipality'=> 'San Lorenzo'],
			['id_departament' => 10,'municipality'=> 'Samayac'],
			['id_departament' => 10,'municipality'=> 'San Pablo Jocopilas'],
			['id_departament' => 10,'municipality'=> 'San Antonio Suchitepéquez'],
			['id_departament' => 10,'municipality'=> 'San Miguel Panám'],
			['id_departament' => 10,'municipality'=> 'San Gabriel'],
			['id_departament' => 10,'municipality'=> 'Chicacao'],
			['id_departament' => 10,'municipality'=> 'Patulul'],
			['id_departament' => 10,'municipality'=> 'Santa Bárbara'],
			['id_departament' => 10,'municipality'=> 'San Juan Bautista'],
			['id_departament' => 10,'municipality'=> 'Santo Tomas La Unión'],
			['id_departament' => 10,'municipality'=> 'Zunilito'],
			['id_departament' => 10,'municipality'=> 'Pueblo Nuevo'],
			['id_departament' => 10,'municipality'=> 'Rio Bravo'],
			['id_departament' => 11,'municipality'=> 'Retalhuleu'],
			['id_departament' => 11,'municipality'=> 'San Sebastián'],
			['id_departament' => 11,'municipality'=> 'Santa Cruz Mulua'],
			['id_departament' => 11,'municipality'=> 'San Martin Zapotitlán'],
			['id_departament' => 11,'municipality'=> 'San Felipe'],
			['id_departament' => 11,'municipality'=> 'San Andrés Villa Seca'],
			['id_departament' => 11,'municipality'=> 'Champerico'],
			['id_departament' => 11,'municipality'=> 'Nuevo San Carlos'],
			['id_departament' => 11,'municipality'=> 'El Asintal '],
			['id_departament' => 12,'municipality'=> 'San Marcos'],
			['id_departament' => 12,'municipality'=> 'San Pedro Sacatepéquez'],
			['id_departament' => 12,'municipality'=> 'San Antonio Sacatepéquez'],
			['id_departament' => 12,'municipality'=> 'Comitancillo'],
			['id_departament' => 12,'municipality'=> 'San Miguel Ixtahuacán'],
			['id_departament' => 12,'municipality'=> 'Concepción Tutuapa'],
			['id_departament' => 12,'municipality'=> 'Tacana'],
			['id_departament' => 12,'municipality'=> 'Sibinal'],
			['id_departament' => 12,'municipality'=> 'Tajumulco'],
			['id_departament' => 12,'municipality'=> 'Tejutla'],
			['id_departament' => 12,'municipality'=> 'San Rafael Pie De La Cuesta'],
			['id_departament' => 12,'municipality'=> 'Nuevo Progreso'],
			['id_departament' => 12,'municipality'=> 'El Tumbador'],
			['id_departament' => 12,'municipality'=> 'San José El Rodeo'],
			['id_departament' => 12,'municipality'=> 'Malacatán'],
			['id_departament' => 12,'municipality'=> 'Catarina'],
			['id_departament' => 12,'municipality'=> 'Ayutla (Tecún Uman)'],
			['id_departament' => 12,'municipality'=> 'Ocos'],
			['id_departament' => 12,'municipality'=> 'San Pablo'],
			['id_departament' => 12,'municipality'=> 'El Quetzal'],
			['id_departament' => 12,'municipality'=> 'La Reforma'],
			['id_departament' => 12,'municipality'=> 'Pajapita'],
			['id_departament' => 12,'municipality'=> 'Ixchiguán'],
			['id_departament' => 12,'municipality'=> 'San José Ojetenan'],
			['id_departament' => 12,'municipality'=> 'San Cristóbal Cucho'],
			['id_departament' => 12,'municipality'=> 'Sipacapa'],
			['id_departament' => 12,'municipality'=> 'Esquipulas Palo Gordo'],
			['id_departament' => 12,'municipality'=> 'Rio Blanco'],
			['id_departament' => 12,'municipality'=> 'San Lorenzo'],
			['id_departament' => 13,'municipality'=> 'Huehuetenango'],
			['id_departament' => 13,'municipality'=> 'Chiantla'],
			['id_departament' => 13,'municipality'=> 'Malacatancito'],
			['id_departament' => 13,'municipality'=> 'Cuilco'],
			['id_departament' => 13,'municipality'=> 'Nentón'],
			['id_departament' => 13,'municipality'=> 'San Pedro Necta'],
			['id_departament' => 13,'municipality'=> 'Jacaltenango'],
			['id_departament' => 13,'municipality'=> 'San Pedro Soloma'],
			['id_departament' => 13,'municipality'=> 'San Ildefonso Ixtahuacán'],
			['id_departament' => 13,'municipality'=> 'Santa Bárbara'],
			['id_departament' => 13,'municipality'=> 'La Libertad'],
			['id_departament' => 13,'municipality'=> 'La Democracia'],
			['id_departament' => 13,'municipality'=> 'San Miguel Acatan'],
			['id_departament' => 13,'municipality'=> 'San Rafael La Independencia'],
			['id_departament' => 13,'municipality'=> 'Todos Santos Cuchumatán'],
			['id_departament' => 13,'municipality'=> 'San Juan Atitán'],
			['id_departament' => 13,'municipality'=> 'Santa Eulalia'],
			['id_departament' => 13,'municipality'=> 'San Mateo Ixtatán'],
			['id_departament' => 13,'municipality'=> 'Colotenango'],
			['id_departament' => 13,'municipality'=> 'San Sebastián Huehuetenango'],
			['id_departament' => 13,'municipality'=> 'Tectitán'],
			['id_departament' => 13,'municipality'=> 'Concepción Huista'],
			['id_departament' => 13,'municipality'=> 'San Juan Ixcoy'],
			['id_departament' => 13,'municipality'=> 'San Antonio Huista'],
			['id_departament' => 13,'municipality'=> 'San Sebastián Coatán'],
			['id_departament' => 13,'municipality'=> 'Santa Cruz Barillas'],
			['id_departament' => 13,'municipality'=> 'Aguacatán'],
			['id_departament' => 13,'municipality'=> 'San Rafael Petzal'],
			['id_departament' => 13,'municipality'=> 'San Gaspar Ixchil'],
			['id_departament' => 13,'municipality'=> 'Santiago Chimaltenango'],
			['id_departament' => 13,'municipality'=> 'Santa Ana Huista '],
			['id_departament' => 14,'municipality'=> 'Santa Cruz Del Quiche'],
			['id_departament' => 14,'municipality'=> 'Chiche'],
			['id_departament' => 14,'municipality'=> 'Chinique'],
			['id_departament' => 14,'municipality'=> 'Zacualpa'],
			['id_departament' => 14,'municipality'=> 'Chajul'],
			['id_departament' => 14,'municipality'=> 'Santo Tomas Chichicastenango'],
			['id_departament' => 14,'municipality'=> 'Patzité'],
			['id_departament' => 14,'municipality'=> 'San Antonio Ilotenango'],
			['id_departament' => 14,'municipality'=> 'San Pedro Jocopilas'],
			['id_departament' => 14,'municipality'=> 'Cunen'],
			['id_departament' => 14,'municipality'=> 'San Juan Cotzal'],
			['id_departament' => 14,'municipality'=> 'Joyabaj'],
			['id_departament' => 14,'municipality'=> 'Nebaj'],
			['id_departament' => 14,'municipality'=> 'San Andrés Sajcabajá'],
			['id_departament' => 14,'municipality'=> 'San Miguel Uspantán'],
			['id_departament' => 14,'municipality'=> 'Sacapulas'],
			['id_departament' => 14,'municipality'=> 'San Bartolomé Jocotenango'],
			['id_departament' => 14,'municipality'=> 'Canilla'],
			['id_departament' => 14,'municipality'=> 'Chicamán'],
			['id_departament' => 14,'municipality'=> 'Ixcán'],
			['id_departament' => 14,'municipality'=> 'Pachalum'],
			['id_departament' => 14,'municipality'=> 'Playa Grande'],
			['id_departament' => 15,'municipality'=> 'Salamá'],
			['id_departament' => 15,'municipality'=> 'San Miguel Chicaj'],
			['id_departament' => 15,'municipality'=> 'Rabinal'],
			['id_departament' => 15,'municipality'=> 'Cubulco'],
			['id_departament' => 15,'municipality'=> 'Granados'],
			['id_departament' => 15,'municipality'=> 'Santa Cruz El Chol'],
			['id_departament' => 15,'municipality'=> 'San Jerónimo'],
			['id_departament' => 15,'municipality'=> 'Purulhá'],
			['id_departament' => 16,'municipality'=> 'Cobán'],
			['id_departament' => 16,'municipality'=> 'Santa Cruz Verapaz'],
			['id_departament' => 16,'municipality'=> 'San Cristóbal Verapaz'],
			['id_departament' => 16,'municipality'=> 'Tactic'],
			['id_departament' => 16,'municipality'=> 'Tamahú'],
			['id_departament' => 16,'municipality'=> 'San Miguel Tucurú'],
			['id_departament' => 16,'municipality'=> 'Panzós'],
			['id_departament' => 16,'municipality'=> 'Senahú'],
			['id_departament' => 16,'municipality'=> 'San Pedro Carcha'],
			['id_departament' => 16,'municipality'=> 'San Juan Chamelco'],
			['id_departament' => 16,'municipality'=> 'Lanquín'],
			['id_departament' => 16,'municipality'=> 'Santa María Cahabón'],
			['id_departament' => 16,'municipality'=> 'Chisec'],
			['id_departament' => 16,'municipality'=> 'Chahal'],
			['id_departament' => 16,'municipality'=> 'Fray Bartolomé De Las Casas'],
			['id_departament' => 16,'municipality'=> 'La Tinta'],
			['id_departament' => 16,'municipality'=> 'Raxruhá'],
			['id_departament' => 17,'municipality'=> 'Flores'],
			['id_departament' => 17,'municipality'=> 'San José'],
			['id_departament' => 17,'municipality'=> 'San Benito'],
			['id_departament' => 17,'municipality'=> 'San Andrés'],
			['id_departament' => 17,'municipality'=> 'La Libertad'],
			['id_departament' => 17,'municipality'=> 'San Francisco'],
			['id_departament' => 17,'municipality'=> 'Santa Ana'],
			['id_departament' => 17,'municipality'=> 'Dolores'],
			['id_departament' => 17,'municipality'=> 'San Luis'],
			['id_departament' => 17,'municipality'=> 'Sayaxché'],
			['id_departament' => 17,'municipality'=> 'Melchor De Mencos'],
			['id_departament' => 17,'municipality'=> 'Poptún '],
			['id_departament' => 18,'municipality'=> 'Puerto Barrios'],
			['id_departament' => 18,'municipality'=> 'Livingston'],
			['id_departament' => 18,'municipality'=> 'El Estor'],
			['id_departament' => 18,'municipality'=> 'Morales'],
			['id_departament' => 18,'municipality'=> 'Los Amates'],
			['id_departament' => 19,'municipality'=> 'Zacapa'],
			['id_departament' => 19,'municipality'=> 'Estanzuela'],
			['id_departament' => 19,'municipality'=> 'Rio Hondo'],
			['id_departament' => 19,'municipality'=> 'Gualan'],
			['id_departament' => 19,'municipality'=> 'Teculután'],
			['id_departament' => 19,'municipality'=> 'Usumatlán'],
			['id_departament' => 19,'municipality'=> 'Cabañas'],
			['id_departament' => 19,'municipality'=> 'San Diego'],
			['id_departament' => 19,'municipality'=> 'La Unión'],
			['id_departament' => 19,'municipality'=> 'Huite'],
			['id_departament' => 20,'municipality'=> 'Chiquimula'],
			['id_departament' => 20,'municipality'=> 'San José La Arada'],
			['id_departament' => 20,'municipality'=> 'San Juan La Ermita'],
			['id_departament' => 20,'municipality'=> 'Jocotán'],
			['id_departament' => 20,'municipality'=> 'Camotán'],
			['id_departament' => 20,'municipality'=> 'Olopa'],
			['id_departament' => 20,'municipality'=> 'Esquipulas'],
			['id_departament' => 20,'municipality'=> 'Concepción Las Minas'],
			['id_departament' => 20,'municipality'=> 'Quezaltepeque'],
			['id_departament' => 20,'municipality'=> 'San Jacinto'],
			['id_departament' => 20,'municipality'=> 'Ipala'],
			['id_departament' => 21,'municipality'=> 'Jalapa'],
			['id_departament' => 21,'municipality'=> 'San Pedro Pinula'],
			['id_departament' => 21,'municipality'=> 'San Luis Jilotepeque'],
			['id_departament' => 21,'municipality'=> 'San Manuel Chaparron'],
			['id_departament' => 21,'municipality'=> 'San Carlos Alzatate'],
			['id_departament' => 21,'municipality'=> 'Monjas'],
			['id_departament' => 21,'municipality'=> 'Mataquescuintla'],
			['id_departament' => 22,'municipality'=> 'Jutiapa'],
			['id_departament' => 22,'municipality'=> 'El Progreso'],
			['id_departament' => 22,'municipality'=> 'Santa Catarina Mita'],
			['id_departament' => 22,'municipality'=> 'Agua Blanca'],
			['id_departament' => 22,'municipality'=> 'Asunción Mita'],
			['id_departament' => 22,'municipality'=> 'Yupiltepeque'],
			['id_departament' => 22,'municipality'=> 'Atescatempa'],
			['id_departament' => 22,'municipality'=> 'Jerez'],
			['id_departament' => 22,'municipality'=> 'El Adelanto'],
			['id_departament' => 22,'municipality'=> 'Zapotitlán'],
			['id_departament' => 22,'municipality'=> 'Comapa'],
			['id_departament' => 22,'municipality'=> 'Jalpatagua'],
			['id_departament' => 22,'municipality'=> 'Conguaco'],
			['id_departament' => 22,'municipality'=> 'Moyuta'],
			['id_departament' => 22,'municipality'=> 'Pasaco'],
			['id_departament' => 22,'municipality'=> 'San José Acate'],
			['id_departament' => 22,'municipality'=> 'Quesada'],


        	]);
    }
}
